django_peo/urls.py
import logging

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path, re_path

from unical_template.views import *

logger = logging.getLogger(__name__)

# admin labels
admin.site.site_header = 'Amministrazione'
admin.site.pretitle    = 'pretitle in urls.py'
admin.site.site_title  = 'Pannello di amministrazione'

urlpatterns = [
    path('gestione/', admin.site.urls),
    path('logout/', logout_view, name='logout'),
    path('500/', test_500, name='test_500'),
    path('timeout/<seconds>', test_timeout, name='test_timeout'),
]

handler500 = error_500

if settings.DEBUG:
    # STATICS FILE SERVE
    from django.views.static import serve
    urlpatterns.append(
        path('{}/<path>'.format(settings.STATIC_URL[1:-1]),
            serve,
            {'document_root': settings.STATIC_ROOT,
             'show_indexes' : True})
    )
    # MEDIA FILE SERVE
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    # protected download in production environment
    urlpatterns.append(
        # [1:] avoids: (urls.W002) Your URL pattern '/media//<path>' has a route beginning with a '/'
        re_path('{}/(?P<path>[a-zA-Z0-9\_\-\.1\/]+)'.format(settings.MEDIA_URL[1:-1]),
                protected_serve, name='protected_download')
    )
    urlpatterns.append(
        # [1:] avoids: (urls.W002) Your URL pattern '/media//<path>' has a route beginning with a '/'
        re_path('{}{}/(?P<path>[a-zA-Z0-9\_\-\.1\/]+)'.format(settings.HOSTNAME,
                                                              settings.MEDIA_URL[1:-1]),
                protected_serve, name='protected_download')
    )


if 'adminactions' in settings.INSTALLED_APPS:
    from django.contrib.admin import site
    import adminactions.actions as actions
    import adminactions.urls
    urlpatterns += path('adminactions/', include((adminactions.urls, 'adminactions'))),
    actions.add_to_site(site)

if 'advanced_filters' in settings.INSTALLED_APPS:
    import advanced_filters.urls
    urlpatterns += path('advanced_filters/', include((advanced_filters.urls, 'advanced_filters'))),

# Esempio di come includere gli urls delle app solo se queste sono installate
if 'nested_admin' in settings.INSTALLED_APPS:
    import nested_admin.views
    urlpatterns += path('server-data\.js', nested_admin.views.server_data_js,
                        name="nesting_server_data"),

if 'unical_template' in settings.INSTALLED_APPS:
    import unical_template.urls
    urlpatterns += path('template/', include(unical_template.urls, namespace='unical_template')),

if 'gestione_risorse_umane' in settings.INSTALLED_APPS:
    import gestione_risorse_umane.urls
    urlpatterns += path('', include(gestione_risorse_umane.urls, namespace='risorse_umane')),

if 'gestione_peo' in settings.INSTALLED_APPS:
    import gestione_peo.urls
    urlpatterns += path('', include(gestione_peo.urls, namespace='gestione_peo')),

if 'domande_peo' in settings.INSTALLED_APPS:
    import domande_peo.urls
    urlpatterns += path('', include(domande_peo.urls, namespace='domande_peo')),

if 'saml2_sp' in settings.INSTALLED_APPS:
    import saml2_sp.urls
    urlpatterns += path('', include((saml2_sp.urls, 'sp',))),

domande_peo/urls.py
from django.urls import path
from wkhtmltopdf.views import PDFTemplateView

from .views import *

app_name="domande_peo"

urlpatterns = [
    path('bando/<str:bando_id>/domanda/aggiungi/<int:descrizione_indicatore_id>/',
         aggiungi_titolo, name='aggiungi_titolo'),

    path('bando/<str:bando_id>/domanda/modifica/<int:modulo_compilato_id>/',
          modifica_titolo, name='modifica_titolo'),

    path('bando/<str:bando_id>/cancella/domanda/<int:domanda_bando_id>/',
          cancella_domanda, name='cancella_domanda'),

    path('bando/<str:bando_id>/domanda/cancella/modulo/<int:modulo_compilato_id>/',
          cancella_titolo, name='cancella_titolo'),

    path('bando/<str:bando_id>/domanda/',
         dashboard_domanda, name='dashboard_domanda'),
         
    path('bando/<str:bando_id>/domanda/aggiungi',
         scelta_titolo_da_aggiungere, name='scelta_titolo_da_aggiungere'),
        
    path('bando/<int:bando_id>/anteprima/<int:descrizione_indicatore_id>/',
         anteprima_modulo_inserimento, name='anteprima_modulo_inserimento'),
        
    path('bando/<int:bando_id>/anteprima-utente/<int:descrizione_indicatore_id>/',
         anteprima_modulo_inserimento_frontend, name='anteprima_modulo_inserimento_frontend'),

    path('bando/<str:bando_id>/vedi/<int:modulo_domanda_bando_id>/',
         vedi_modulo_inserito, name='vedi_modulo_inserito'),
    
    path('bando/<str:bando_id>/accetta-condizioni/',
         accetta_condizioni_bando, name='accetta_condizioni_bando'), 
         
    path('bando/<str:bando_id>/modifica/<int:modulo_compilato_id>/elimina_allegato/<str:allegato>/',
         elimina_allegato, name='elimina_allegato'), 
         
    path('bando/<str:bando_id>/<int:modulo_compilato_id>/download_allegato/<str:allegato>/',
         download_allegato, name='download_allegato'), 
         
    #path('bando/<str:bando_id>/riepilogo_domanda/<int:domanda_bando_id>/',
    #     PDFTemplateView.as_view(template_name='top_notify.html',
    #                             filename='riepilogo.pdf'), 
    #     name='riepilogo_domanda_pdf'),
    
    path('bando/<str:bando_id>/domanda/riepilogo/<int:domanda_bando_id>/',
          riepilogo_domanda, name='riepilogo_domanda'), 

    path('bando/<str:bando_id>/<int:modulo_compilato_id>/download_pdf',
          download_modulo_inserito_pdf, name='download_modulo_inserito_pdf'),

    path('bando/<str:bando_id>/riepilogo_domanda/<int:domanda_bando_id>/download_pdf',
          download_domanda_pdf, name='download_domanda_pdf'),

    path('bando/<str:bando_id>/domanda/<int:domanda_bando_id>/<str:azione>/',
          chiudi_apri_domanda, name='chiudi_apri_domanda'),

]

gestione_peo/urls.py
from django.urls import path
from .views import *

app_name="gestione_peo"

urlpatterns = [
    path('bandi/<str:bando_id>/', dettaglio_bando_peo, name='dettaglio_bando_peo'),
    path('bandi', bandi_peo, name='bandi_peo'),
    path('bandi/import_file', import_file, name='import_file'),
    path('bandi/<str:bando_id>/avvisi/<int:avviso_id>/download/', download_avviso, name='download_avviso'),

    # Commissione bando
    path('commissioni', commissioni, name='commissioni'),
    path('commissioni/<int:commissione_id>/', commissione_dettaglio, name='dettaglio_commissione'),
    path('commissioni/<int:commissione_id>/gestisci', commissione_manage, name='manage_commissione'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>', commissione_domanda_manage, name='commissione_domanda_manage'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/extended', commissione_domanda_manage_extended, name='commissione_domanda_manage_extended'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/download_allegato/<str:allegato>/',commissione_download_allegato, name='commissione_download_allegato'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/elimina_allegato/<str:allegato>/',commissione_elimina_allegato, name='commissione_elimina_allegato'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/abilita', commissione_abilita_domanda, name='commissione_abilita_domanda'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/disabilita', commissione_disabilita_domanda, name='commissione_disabilita_domanda'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/aggiungi', commissione_domanda_scegli_titolo, name='commissione_domanda_scegli_titolo'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/aggiungi/<int:descrizione_indicatore_id>', commissione_domanda_aggiungi_titolo, name='commissione_domanda_aggiungi_titolo'),

    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/duplica', commissione_domanda_duplica_titolo, name='commissione_domanda_duplica_titolo'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/duplica/<int:descrizione_indicatore_id>', commissione_domanda_duplica_titolo_confirm, name='commissione_domanda_duplica_titolo_confirm'),

    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/modifica', commissione_modulo_domanda_modifica, name='commissione_modulo_domanda_modifica'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/cancella', commissione_cancella_titolo, name='commissione_cancella_titolo'),
]

saml2_sp/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import logout

from . import views

urlpatterns = [
    path('', views.index),
    path('logout/', logout),
    path('saml2/', include('djangosaml2.urls')),
]

unical_template/urls.py
from django.urls import path
from .views import *

app_name="unical_template"

urlpatterns = [
    path('base', base_template, name='base'),
    path('dashboard', dashboard_template, name='dashboard'),
]

domande_peo/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from django.forms.fields import DateField

from .models import *
from gestione_peo.models import *


class GenericPeoForm(forms.Form):
    numero_di_protocollo =  forms.CharField(label='Numero di Protocollo',
                                            max_length='8',
                                            widget=forms.TextInput(attrs={'class':'CUSTOM'}))
    anno_protocollo = forms.IntegerField(widget=forms.TextInput(attrs={'class':'CUSTOM'}))
    data_inizio = forms.DateField(widget=forms.TextInput(attrs={'type':'date',
                                                                'class':'CUSTOM'}))
    data_fine = forms.DateField(widget=forms.TextInput(attrs={'type':'date',
                                                              'class':'CUSTOM'}))


class AccettazioneClausoleForm(forms.Form):
	accettazione = forms.BooleanField(label='')


class AllegatoForm(forms.Form):
    allegato = forms.FileField(label='Allegato')


class TitoliForm(forms.Form):
    denominazione_titolo = forms.CharField(label='Denominazione del Titolo',
                                           max_length='200')
    tipologia_titolo = forms.ModelChoiceField(queryset=Bando.objects.all(),
                                              label='Tipologia Titolo')


class TitoloPeoForm(AllegatoForm, TitoliForm, GenericPeoForm):
    pass


class IncaricoPeoForm(AllegatoForm, TitoliForm, GenericPeoForm):
    pass


class PrestazioniIndividualiForm(AllegatoForm, TitoliForm, GenericPeoForm):
    pass

domande_peo/templates/buttons_domanda_peo.html
{% if not domanda_bando.bando.presentazione_domande_scaduta and domanda_bando.is_aperta %}
<div class="row " style="margin:20px 0;">
    <a href="{% url 'domande_peo:scelta_titolo_da_aggiungere' bando_id=domanda_bando.bando.slug%}">
        <div class="ui right floated labeled icon positive button">
            <i class="plus circle icon"></i>
            Aggiungi Modulo
        </div>
    </a>
</div>
{% endif %}

<div style="margin:20px 0;">
    {% if not domanda_bando.bando.presentazione_domande_scaduta and domanda_bando.is_aperta and not domanda_bando.descr_ind_non_cancellabili %}
        <div class="ui red button" id="but_cancella_domanda_{{domanda_bando.pk}}">
            <i class="delete icon"></i> Distruggi la tua Domanda
        </div>
    {% endif %}

    <a href="{% url 'domande_peo:riepilogo_domanda' bando_id=domanda_bando.bando.pk domanda_bando_id=domanda_bando.pk  %}">
        <div class="ui button">
            <i class="print icon"></i> Riepilogo
        </div>
    </a>

    {% if not domanda_bando.bando.presentazione_domande_scaduta and domanda_bando.is_aperta %}

        {% if domanda_bando.valida %}
         <div class="ui right floated labeled icon positive button lockbutton" id="but_chiudi_domanda_{{domanda_bando.pk}}">
            <i class="arrow alternate envelope outline icon"></i>
            {% if domanda_bando.bando.protocollo_required %}
                Concludi e Protocolla
            {% else %}
                Concludi
            {% endif %}
        </div>

        {% else %}
        <div class="ui right floated orange button" id="check_chiudi_domanda_{{domanda_bando.pk}}">
            <i class="pencil alternate icon"></i>
            Domanda non completa
        </div>
        {% endif %}

    {% elif not domanda_bando.bando.presentazione_domande_scaduta %}

        {% if domanda_bando.rettificabile %}
        <div class="ui right floated orange button lockbutton" id="but_rettifica_domanda_{{domanda_bando.pk}}">
            <i class="pencil alternate icon"></i>
            Riapri la domanda per una Rettifica
        </div>
        {% endif %}

    {% endif %}

</div>

domande_peo/templates/modal_dialogs_domanda.html
<!--
Modal Inserimento delete
-->
{% for ins in domanda_bando.modulodomandabando_set.all %}
<div class="ui basic modal" id="modal_ind_{{ ins.pk }}">
    <div class="ui icon header">
        <i class="trash alternate icon"></i>
        Cancellazione inserimento
        <h5>
            <b>{{ ins.get_identificativo_veloce }}</b>
            <br>
            {{ ins.descrizione_indicatore.nome }}
        </h5>
    </div>
    <div class="content">
        <p>Stai per cancellare definitamente questo
            inserimento, creato da
            te giorno {{ ins.created }},
            dalla tua domanda {{ ins.domanda_bando.bando }}.
        </p>
        <h5>
            Sei veramente sicuro di questa scelta?
        </h5>
    </div>
    <div class="actions">
        <div class="ui white basic cancel inverted button">
            <i class="remove icon"></i>
            No
        </div>

        <a style="color: white;" href="{% url 'domande_peo:cancella_titolo' bando_id=ins.domanda_bando.bando.pk modulo_compilato_id=ins.pk  %}">
            <div class="ui red ok inverted button">
                <i class="checkmark icon"></i>
                Si, sono sicuro: CANCELLA
            </div>
        </a>

    </div>
</div>
{% endfor %}

<!--
Modal Domanda delete
-->
<div class="ui basic modal" id="cancella_domanda_{{ domanda_bando.pk}}">
    <div class="ui icon header">
        <i class="trash alternate icon"></i>
        Cancellazione Domanda {{ bando }}
        <h5>{{ domanda_bando }}</h5>
    </div>
    <div class="content">
        <p>Stai per cancellare per intero la tua domanda {{ bando }},
            creata da te giorno {{ domanda_bando.created }}.
        </p>
        <h5>
            Sei veramente sicuro di questa scelta?
        </h5>
    </div>
    <div class="actions">
        <div class="ui white basic cancel inverted button">
            <i class="remove icon"></i>
            No
        </div>

        <a style="color: white;" href="{% url 'domande_peo:cancella_domanda' bando_id=domanda_bando.bando.pk domanda_bando_id=domanda_bando.pk %}">
            <div class="ui red ok inverted button">
                <i class="checkmark icon"></i>
                Si, sono sicuro: CANCELLA
            </div>
        </a>

    </div>
</div>


<!--
Modal Domanda chiusura
-->
<div class="ui basic modal" id="chiudi_domanda_{{ domanda_bando.pk}}">
    <div class="ui icon header">
        <i class="envelope outline icon"></i>
        Presentazione Domanda {{ bando }}
        <h5>{{ domanda_bando }}</h5>
    </div>
    <div class="content">
        <p>Stai per <i>concludere e presentare ufficialmente</i> la tua domanda {{ bando }},
            creata da te giorno {{ domanda_bando.created }}.
        </p>
        <p>
            Questo significa che hai completato la tua redazione
            {% if bando.protocollo_required %}
            ,
            <u>
            inoltre
            ti appresti a presentare la domanda mediante protocollo informatico.
            </u>
            {% endif %}
        </p>

        <p>
            Se in seguito vorrai rettificare la tua Domanda di partecipazione
            potrai riaprirla e modificarla a condizione che i termini della sua consegna non siano scaduti.
            Il sistema terrà traccia della rettifica memorizzando lo storico delle tue azioni.
        </p>
        <h5>
            Sei veramente sicuro di questa scelta?
        </h5>
    </div>
    <div class="actions">
        <div class="ui white basic cancel inverted button">
            <i class="remove icon"></i>
            No
        </div>

        <a style="color: white;" class="lockbutton_trigger" id="but_confirm_chiudi_domanda_{{ domanda_bando.pk }}" href="{% url 'domande_peo:chiudi_apri_domanda' bando_id=domanda_bando.bando.pk domanda_bando_id=domanda_bando.pk azione='chiudi' %}">
            <div class="ui green ok inverted button">
                <i class="checkmark icon"></i>
                Si, sono sicuro: La domanda è completa e posso marcarla come conclusa.
            </div>
        </a>

    </div>
</div>

<!--
Modal Domanda check moduli mancanti
-->
<div class="ui basic modal" id="check_domanda_{{ domanda_bando.pk}}">
    <div class="ui icon header">
        <i class="hand point right outline icon"></i>
        Correzione Domanda {{ bando }}
        <h5>{{ domanda_bando }}</h5>
    </div>
    <div class="content">
        <p>Risulta che la tua Domanda sia da completare o richieda una correzione prima della chiusura.
        </p>

        {% if domanda_bando.indicatori_richiesti %}
        <p>I seguenti Indicatori sono richiesti ma non risultano essere stati ancora caricati. Clicca su di essi per accedere velocemente alla loro compilazione:</p>
        <p>Clicca su di essi per accedere velocemente alla loro compilazione.</p>
        <div class="ui relaxed divided list" style="padding: 1%;">
            {% for i in domanda_bando.indicatori_richiesti %}
                <div class="item">
                    <a style="color: orange;" href="{% url 'domande_peo:aggiungi_titolo' bando_id=bando.slug descrizione_indicatore_id=i.id %}">
                        - {{ i }}
                    </a>
                </div>
            {% endfor %}
        </div>
        {% endif %}

        {% if domanda_bando.moduli_non_validi %}
        <p>I seguenti Moduli risultano essere stati compilati in maniera non valida:</p>
        <div class="ui relaxed divided list" style="padding: 1%;">
            {% for mod in domanda_bando.moduli_non_validi %}
                <div class="item">
                    <a  style="color: orange;"  href="{% url 'domande_peo:modifica_titolo' bando_id=bando.slug modulo_compilato_id=mod.id %}">
                        - {{ mod.descrizione_indicatore }}
                    </a>
                </div>
            {% endfor %}
        </div>
        {% endif %}
        <h5>
            Ti preghiamo di correggere la domanda prima di concluderla e consegnarla.
        </h5>
    </div>
    <div class="actions">
        <a style="color: white;" href="{% url 'domande_peo:dashboard_domanda' bando_id=domanda_bando.bando.pk %}">
            <div class="ui green ok inverted button">
                <i class="checkmark icon"></i>
                Ho capito
            </div>
        </a>

    </div>
</div>

<!--
Modal Rettifica Domanda
-->
<div class="ui basic modal" id="rettifica_domanda_{{ domanda_bando.pk}}">
    <div class="ui icon header">
        <i class="redo icon"></i>
        Rettifica Domanda {{ bando }}
        <h5>{{ domanda_bando }}</h5>
    </div>
    <div class="content">
        <p>Stai per <i>riaprire e rettificare</i> la tua domanda {{ bando }},
            creata da te giorno {{ domanda_bando.created }} e chiusa da te giorno {{ domanda_bando.data_chiusura }}.
        </p>
        <p> Ricordati di chiudere e presentare la tua domanda nuovamente altrimenti questa non verrà ritenuta valida.
        </p>
        <h5>
            Sei veramente sicuro di questa scelta?
        </h5>
    </div>
    <div class="actions">
        <div class="ui white basic cancel inverted button">
            <i class="remove icon"></i>
            No
        </div>

        <a style="color: white;" class="lockbutton_trigger" id="but_confirm_rettifica_domanda_{{ domanda_bando.pk }}" href="{% url 'domande_peo:chiudi_apri_domanda' bando_id=domanda_bando.bando.pk domanda_bando_id=domanda_bando.id azione='riapri' %}">
            <div class="ui green ok inverted button">
                <i class="checkmark icon"></i>
                Si, sono sicuro: Desidero rettificare la mia Domanda di Partecipazione.
            </div>
        </a>

    </div>
</div>

domande_peo/templates/modulo_form_modifica.html
{% extends 'modulo_form.html' %}

{% load domande_peo_tags %}
{% load django_form_builder_tags %}
{% load i18n %}

{% block add_another %}
    {% domanda_bando_num_max_descrind modulo_domanda_bando.domanda_bando modulo_domanda_bando.descrizione_indicatore as max_inserimenti %}
    {% if "success" in message.tags and not max_inserimenti %}
        <div style="padding-top: 13px;">
            <a href="{% url 'domande_peo:aggiungi_titolo' bando_id=bando.slug descrizione_indicatore_id=modulo_domanda_bando.descrizione_indicatore.pk %}">
            <div class="ui button green">
                <i class="plus square outline icon icon"></i>
                Aggiungi un altro modulo dello stesso tipo
            </div>
            </a>
        </div>
    {% endif %}
{% endblock add_another %}

    {% block descrizione_indicatore %}
        {% if modulo_domanda_bando.descrizione_indicatore.note %}
            <div class="ui">
                {{ modulo_domanda_bando.descrizione_indicatore.note_as_html|safe }}
            </div>
        {% endif %}
        {% block top_buttons %}{% endblock top_buttons %}
    {% endblock descrizione_indicatore %}

{% block formbuttons_back %}
    <a href="{% url 'domande_peo:dashboard_domanda' bando.slug %}#{{ bando.slug }}">
        <div class="ui button">
            <i class="step backward icon"></i>
            Torna alla Domanda
        </div>
    </a>
{% endblock formbuttons_back %}

{% block formbuttons_pdf %}
    <a href="{% url 'domande_peo:download_modulo_inserito_pdf' bando_id=bando.slug modulo_compilato_id=modulo_domanda_bando.pk %}">
        <div class="ui button">
            <i class="file pdf icon"></i>
            Scarica PDF
        </div>
    </a>
{% endblock formbuttons_pdf %}


<!--
Se la domanda è modificabile,
il pulsante Salva e gli script 'modal' per
la cancellazione degli allegati vengono prodotti
-->
{% block submit_button %}
    {% if modulo_domanda_bando.domanda_bando.modificabile %}
        <input class="ui button green" type="submit" value="Salva" />
    {% endif %}
{% endblock submit_button %}

{% block bottom_scripts %}
    {{ block.super }}
    {% if allegati and modulo_domanda_bando.domanda_bando.modificabile %}
        <script type="text/javascript">
            $(function () {
                {% for k,v in allegati.items %}
                $("#cancella_allegato_{{ k }}").click(function () {
                    $('#modal_allegato_{{ k }}')
                        .modal('show');
                });
                {% endfor %}
            });
        </script>
    {% endif %}
{% endblock %}


{% block allegati %}
    <!--
    Se ci sono allegati inseriti
    -->
    {% if allegati %}
        <h3>Allegati:</h3>
        <table class="ui compact striped table">
            <tbody>
                <tr>
                    <th>{% trans "Nome Allegato" %}</th>
                    <th>{% trans "Nome File" %}</th>
                    <th>{% trans "Altre info" %}</th>
                    <th></th>
                    {% if modulo_domanda_bando.domanda_bando.modificabile %}
                        <th></th>
                    {% endif %}
                </tr>
                {% for k,v in allegati.items %}
                    <tr>
                        <td class="collapsing">
                            <b>{{k}}</b>
                        </td>
                        <td>{{v}}</td>
                        <td>
                        {% get_attachment_sign_details form_allegati path_allegati k v as sign_details %}
                        {% if sign_details %}
                            <ul>
                            {% for kk, vv in sign_details.items %}
                                <li>{{ kk }}: {{ vv }}</li>
                            {% endfor %}
                            </ul>
                        {% else %}
                        -
                        {% endif %}
                        </td>
                        <td class="right aligned collapsing">
                            <a download href="{% url 'domande_peo:download_allegato' bando_id=bando.slug modulo_compilato_id=modulo_domanda_bando.pk allegato=k  %}">
                                <div class="ui small button">
                                    <i class="icon download"></i>
                                    Vedi allegato
                                </div>
                            </a>
                        </td>
                        {% if modulo_domanda_bando.domanda_bando.modificabile %}
                        <!--
                        Se la domanda è modificabile,
                        il pulsante Rimuovi allegato viene mostrato
                        -->
                            <td class="right aligned collapsing">
                                <a id="cancella_allegato_{{ k }}" href="#">
                                    <div class="ui negative small button">
                                        <i class="icon trash"></i>
                                        Rimuovi allegato
                                    </div>
                                </a>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <!--
        Modal delete (solo se la domanda è modificabile)
        -->
        {% if modulo_domanda_bando.domanda_bando.modificabile %}
            {% for k,v in allegati.items %}
                <div class="ui basic modal" id="modal_allegato_{{ k }}">
                    <div class="ui icon header">
                        <i class="trash alternate icon"></i>
                        Cancellazione allegato
                        <h5>{{ k }}: {{ v }}</h5>
                    </div>
                    <div class="content">
                        <p>Stai per cancellare definitamente questo
                            allegato, creato da
                            te giorno {{ modulo_domanda_bando.created }},
                            dalla tua domanda {{ modulo_domanda_bando.domanda_bando.bando }}.
                        </p>
                        <h5>
                            Sei veramente sicuro di questa scelta?
                        </h5>
                    </div>
                    <div class="actions">
                        <div class="ui white basic cancel inverted button">
                            <i class="remove icon"></i>
                            No
                        </div>

                        <a style="color: white;" href="{% url 'domande_peo:elimina_allegato' allegato=k bando_id=bando.slug modulo_compilato_id=modulo_domanda_bando.pk  %}">
                            <div class="ui red ok inverted button">
                                <i class="checkmark icon"></i>
                                Si, sono sicuro: CANCELLA
                            </div>
                        </a>

                    </div>
                </div>
            {% endfor %}
        {% endif %}
    {% endif %}
{% endblock allegati %}

domande_peo/templates/modulo_form_readonly.html
{% extends 'modulo_form.html' %}

{% block formbuttons %}
<input class="ui button green" type="submit" value="Inserisci" />
{% endblock %}

domande_peo/templates/modulo_form_readonly_frontend.html
{% extends 'modulo_form.html' %}

{% block formbuttons %}
{% endblock %}