django_peo/urls.py
import logging

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path, re_path

from unical_template.views import *

logger = logging.getLogger(__name__)

# admin labels
admin.site.site_header = 'Amministrazione'
admin.site.pretitle    = 'pretitle in urls.py'
admin.site.site_title  = 'Pannello di amministrazione'

urlpatterns = [
    path('gestione/', admin.site.urls),
    path('logout/', logout_view, name='logout'),
    path('500/', test_500, name='test_500'),
    path('timeout/<seconds>', test_timeout, name='test_timeout'),
]

handler500 = error_500

if settings.DEBUG:
    # STATICS FILE SERVE
    from django.views.static import serve
    urlpatterns.append(
        path('{}/<path>'.format(settings.STATIC_URL[1:-1]),
            serve,
            {'document_root': settings.STATIC_ROOT,
             'show_indexes' : True})
    )
    # MEDIA FILE SERVE
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    # protected download in production environment
    urlpatterns.append(
        # [1:] avoids: (urls.W002) Your URL pattern '/media//<path>' has a route beginning with a '/'
        re_path('{}/(?P<path>[a-zA-Z0-9\_\-\.1\/]+)'.format(settings.MEDIA_URL[1:-1]),
                protected_serve, name='protected_download')
    )
    urlpatterns.append(
        # [1:] avoids: (urls.W002) Your URL pattern '/media//<path>' has a route beginning with a '/'
        re_path('{}{}/(?P<path>[a-zA-Z0-9\_\-\.1\/]+)'.format(settings.HOSTNAME,
                                                              settings.MEDIA_URL[1:-1]),
                protected_serve, name='protected_download')
    )


if 'adminactions' in settings.INSTALLED_APPS:
    from django.contrib.admin import site
    import adminactions.actions as actions
    import adminactions.urls
    urlpatterns += path('adminactions/', include((adminactions.urls, 'adminactions'))),
    actions.add_to_site(site)

if 'advanced_filters' in settings.INSTALLED_APPS:
    import advanced_filters.urls
    urlpatterns += path('advanced_filters/', include((advanced_filters.urls, 'advanced_filters'))),

# Esempio di come includere gli urls delle app solo se queste sono installate
if 'nested_admin' in settings.INSTALLED_APPS:
    import nested_admin.views
    urlpatterns += path('server-data\.js', nested_admin.views.server_data_js,
                        name="nesting_server_data"),

if 'unical_template' in settings.INSTALLED_APPS:
    import unical_template.urls
    urlpatterns += path('template/', include(unical_template.urls, namespace='unical_template')),

if 'gestione_risorse_umane' in settings.INSTALLED_APPS:
    import gestione_risorse_umane.urls
    urlpatterns += path('', include(gestione_risorse_umane.urls, namespace='risorse_umane')),

if 'gestione_peo' in settings.INSTALLED_APPS:
    import gestione_peo.urls
    urlpatterns += path('', include(gestione_peo.urls, namespace='gestione_peo')),

if 'domande_peo' in settings.INSTALLED_APPS:
    import domande_peo.urls
    urlpatterns += path('', include(domande_peo.urls, namespace='domande_peo')),

if 'saml2_sp' in settings.INSTALLED_APPS:
    import saml2_sp.urls
    urlpatterns += path('', include((saml2_sp.urls, 'sp',))),

gestione_peo/urls.py
from django.urls import path
from .views import *

app_name="gestione_peo"

urlpatterns = [
    path('bandi/<str:bando_id>/', dettaglio_bando_peo, name='dettaglio_bando_peo'),
    path('bandi', bandi_peo, name='bandi_peo'),
    path('bandi/import_file', import_file, name='import_file'),
    path('bandi/<str:bando_id>/avvisi/<int:avviso_id>/download/', download_avviso, name='download_avviso'),

    # Commissione bando
    path('commissioni', commissioni, name='commissioni'),
    path('commissioni/<int:commissione_id>/', commissione_dettaglio, name='dettaglio_commissione'),
    path('commissioni/<int:commissione_id>/gestisci', commissione_manage, name='manage_commissione'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>', commissione_domanda_manage, name='commissione_domanda_manage'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/extended', commissione_domanda_manage_extended, name='commissione_domanda_manage_extended'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/download_allegato/<str:allegato>/',commissione_download_allegato, name='commissione_download_allegato'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/elimina_allegato/<str:allegato>/',commissione_elimina_allegato, name='commissione_elimina_allegato'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/abilita', commissione_abilita_domanda, name='commissione_abilita_domanda'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/disabilita', commissione_disabilita_domanda, name='commissione_disabilita_domanda'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/aggiungi', commissione_domanda_scegli_titolo, name='commissione_domanda_scegli_titolo'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/aggiungi/<int:descrizione_indicatore_id>', commissione_domanda_aggiungi_titolo, name='commissione_domanda_aggiungi_titolo'),

    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/duplica', commissione_domanda_duplica_titolo, name='commissione_domanda_duplica_titolo'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/duplica/<int:descrizione_indicatore_id>', commissione_domanda_duplica_titolo_confirm, name='commissione_domanda_duplica_titolo_confirm'),

    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/modifica', commissione_modulo_domanda_modifica, name='commissione_modulo_domanda_modifica'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/cancella', commissione_cancella_titolo, name='commissione_cancella_titolo'),
]

saml2_sp/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import logout

from . import views

urlpatterns = [
    path('', views.index),
    path('logout/', logout),
    path('saml2/', include('djangosaml2.urls')),
]

unical_template/urls.py
from django.urls import path
from .views import *

app_name="unical_template"

urlpatterns = [
    path('base', base_template, name='base'),
    path('dashboard', dashboard_template, name='dashboard'),
]

unical_template/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _
from model_utils.fields import AutoCreatedField, AutoLastModifiedField

class CreatedModifiedModel(models.Model):
    """
    An abstract base class model that provides self-updating
    ``created`` and ``modified`` fields.
    """
    modified_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True,
                                    related_name="modified-%(app_label)s_%(class)s_related+",
                                    related_query_name="modified-%(app_label)s_%(class)ss+",
                                    on_delete=models.CASCADE, editable=False
                                    )
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True,
                                   related_name="created-%(app_label)s_%(class)s_related+",
                                   related_query_name="created-%(app_label)s_%(class)ss+",
                                   on_delete=models.CASCADE, editable=False
                                   )

    class Meta:
        abstract = True


class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-updating
    ``created`` and ``modified`` fields.
    """
    created = AutoCreatedField(_('created'), editable=False)
    modified = AutoLastModifiedField(_('modified'), editable=False)

    class Meta:
        abstract = True

unical_template/views.py
import logging
import time

from django.conf import settings
from django.contrib import auth
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import (HttpResponseRedirect,
                         HttpResponseForbidden,
                         HttpResponseServerError,
                         HttpResponse)
from django.views.static import serve
from django.shortcuts import render
from django.urls import reverse
from django.utils.http import is_safe_url
from django.shortcuts import get_object_or_404

# Logging
logger = logging.getLogger(__name__)
hdlr = logging.handlers.SysLogHandler( address = '/dev/log',
                                       facility = logging.handlers.SysLogHandler.LOG_USER )
logger.addHandler( hdlr )
formatter = logging.Formatter('%(name)s: %(levelname)s %(message)s')
hdlr.setFormatter( formatter )
logger.setLevel( logging.INFO )

def redirect(request):
    return HttpResponseRedirect('http://www.example.org')

def base_template(request):
    """render the home page"""
    context = {
        "username": '',
        "peer": '',
        "error": "user name e/o password errati"
    }    
    return render(request, "base.html", context=context)

def dashboard_template(request):
    """render the dashboard page"""
    return render(request, "dashboard_peo.html")

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(request.GET.get('next'))

def protected_serve(request, path):
    """
    solo i proprietari degli uploads possono scaricare
    inoltre se è il server stesso a fare una request il download è consentito
    (utile per pdf download via wkhtmltopdf)
    """
    # logger.info('protected download called')
    document_root = settings.MEDIA_ROOT
    # logger.info(document_root)
    # logger.info(path)
    folders = path.split('/')
    
    # logger.info(folders)
    self_request = (request.META.get('REMOTE_ADDR', 0) == \
                    request.META.get('SERVER_ADDR', 1))
    staff_request = request.user.is_staff
    its_owner = False
    if hasattr(request.user, 'matricola'):
        its_owner = request.user.matricola in folders
    
    #logging.info(request.user)
    #logging.info(its_owner)
    
    # check se la matricola dell'utente corrisponde all'utente loggato
    # se REMOTE_ADDRESS == SERVER_ADDR significa che è una richiesta di produzione pdf
    if its_owner or self_request or staff_request:
        #logger.info('{} downloaded "{}"'.format(request.user.matricola, path))
        return serve(request, path, document_root=document_root, show_indexes=False)
    return HttpResponseForbidden()

def test_500(request):
    #return HttpResponseServerError()
    return not_existent_var

def error_500(request):
    return render(request, 'custom_500.html', {})

@login_required
def test_timeout(request, seconds=12):
    time.sleep(int(seconds))
    return HttpResponse('OK,  {} seconds'.format(seconds))

unical_template/templates/base.html
<!DOCTYPE html>
{% load static %}
<head>
    <title>{{ title | default_if_none:"Servizi di rete Ospiti di Ateneo - Universitá della Calabria"}}</title>
    <meta name="description" content="Universitá della Calabria">
    <meta charset="UTF-8">

    <link rel="shortcut icon" href="https://www.unical.it/portale/images/favicon.ico">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    {% block jquery_head %}
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    {% endblock jquery_head %}

    {% block semantic_head %}
    <link href="{% static 'semantic/semantic.min.css' %}" rel="stylesheet">
    <script type="text/javascript" src="{% static 'semantic/semantic.min.js' %}"></script>
    {% endblock semantic_head %}

    <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
    {% block js_head %}{% endblock %}
    {% block extra_head %}{% endblock %}

</head>

<body>

    {% block top_nav %}
        {% include "top_nav.html" %}
    {% endblock top_nav %}

    <div class="container">
        {% block top_bar_icons %}
            {% include "top_bar_icons.html" %}
        {% endblock top_bar_icons %}

        {% block body_content %}
        <div class="row clearfix" style="padding-top:0px;">
            <div class="col-xs-12 column">
                <div class="contenitore_body" style="margin-top: -10px;">
                    <div style="padding: 33px;">

                        {% block messages %}
                            {% if messages %}
                                <ul class="messages">
                                    {% for message in messages %}
                                        <li{% if message.tags %} class="ui {{ message.tags }} message"{% endif %}>
                                            {{ message }}
                                            {% block add_another %}{% endblock add_another %}
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        {% endblock messages %}

                        {% block content %}
                        <h2 style="">Servizio in allestimento</h2>
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
        {% endblock body_content %}

        <div class="row clearfix" style="padding-top:0px;"></div>
    </div> <!-- fine container -->
    {% block bottom_scripts %}{% endblock %}
</body>
</html>

unical_template/templates/custom_500.html
<!DOCTYPE html>
<head>
    <title></title>
    <meta name="description" content="Universitá della Calabria">
    <meta charset="UTF-8">
    
    <link rel="shortcut icon" href="https://www.unical.it/portale/images/favicon.ico">
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">
    
    <script type="text/javascript" src="/static/js/jquery-3.3.1.min.js"></script>
    
    <link href="/static/semantic/semantic.min.css" rel="stylesheet">
    <script type="text/javascript" src="/static/semantic/semantic.min.js"></script>
    
    <script type="text/javascript" src="/static/js/scripts.js"></script>
    
    <script type="text/javascript" src="/static/js/flip.minified.js"></script>

</head>

<body>

    <nav class=" sfondo_bordeaux">
    	<div class="container">
            <div class="row clearfix">
                <div class="col-xs-12">
                    <ul class="elementi_menu" style="margin-top:-5px;">
                        <li style="padding-top:5px;">
                                
                        </li>
                        <li>&nbsp;</li>
                        <li style="background-color:#ECEBE4; height:40px; padding: 0px 2px 0px 2px; width:0px; margin-top:0px;">
                            &nbsp;
                        </li>
                        <li>&nbsp;</li>
                        <li>
                            <a href="https://www.youtube.com/channel/UCnd5Oen95TMO9aLfVRUAABQ">
                                <img src="/static/icons/youtube-icon.png" width="22" alt="Youtube">
                            </a>
                        </li>
                        <li>
                            <a href="https://it-it.facebook.com/pages/Universit%C3%A0-della-Calabria/166678814380">
                                <img src="/static/icons/facebook-icon.png" width="22" alt="Facebook">
                            </a>
                        </li>
                        <li>
                            <a href="https://twitter.com/UnicalPortale">
                                <img src="/static/icons/twitter-icon.png" width="22" alt="Twitter">
                            </a>
                        </li>
                        <li>&nbsp;</li>
                        <li style="background-color:#ECEBE4; height:40px; padding: 0px 2px 0px 2px; width:0px; margin-top:0px;">
                            &nbsp;
                        </li>
                        <li>&nbsp;</li>
                        <li style="padding-top:5px;">
                            <a href="http://www.unicaladmission.it/" title="english version" target="_blank">
                                english version
                                <img src="/static/icons/flag_en.png" alt="RSS Feed">
                            </a>
                        </li>
                        <li>&nbsp;</li>
                        <li style="background-color:#ECEBE4; height:40px; padding: 0px 2px 0px 2px; width:0px; margin-top:0px;">
                            &nbsp;
                        </li>
                        <li>
                            <form class="navbar-form navbar-left" style="margin-top:0px; margin-right:-15px; padding-top:0px;" action="https://www.unical.it/portale/search_results.cfm">
                                <div class="form-group">
                                    <input name="search" class="form-control" type="text" placeholder="cerca" style=" border-radius:0px;">
                                </div>
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row clearfix" style="padding-top:0px;">
            <div class="col-xs-12 column">
                <div class="contenitore_body" style="margin-top: -10px;">
                    <div style="padding: 33px;">
                        
                            <h2 class="ui error">E' stato riscontrato un problema di carattere tecnico.</h2>

                                <h4>Questo può essere causato da uno dei seguenti motivi:</h4>
                            
                                    <ul>
                                        <li>
                                            - Il Database risulta essere momentaneamente non disponibile;
                                        </li>
                                        <li>
                                            - Un aggiornamento del software potrebbe avere generato una eccezione interna;
                                        </li>
                                    </ul>
                                    
                                <p>Un messaggio contenente il tracciato di questo errore è stato inviato allo staff tecnico, appena possibile verrà risolto. Se desideri essere avvisato o ricevere ulteriori informazioni puoi contattare l'ufficio di supporto, altrimenti basterà attendere qualche ora prima che le attività sul sistema riprendano regolarmente.</p>
                                
                                <a href="/" class="ui blue button">go back to Login page »</a>
                        
                    </div>
                </div>
            </div>
        </div>

        <div class="row clearfix" style="padding-top:0px;">

        </div>

    </div> <!-- fine container -->

</body>
</html>

unical_template/templates/custom_message.html
{% extends "base.html" %}

{% block content %}
<h2 class="ui error">Attenzione</h2>
<h5>{{ avviso|safe }}</h5>
    
<a href="javascript:history.back()">
    <div class="ui button">
        <i class="reply icon"></i>
            Torna indietro
    </div>
</a>
        
<a href="{% url 'risorse_umane:dashboard' %}">
    <div class="ui button">
        <i class="home icon"></i>
        Torna alla Pagina Principale
    </div>
</a>

{% endblock %}

unical_template/templates/top_bar_icons.html
{% load static %}
<div class="row clearfix" style="margin-top:2px;">
    <table style="padding:0px; margin:0px;  margin-left:15px; margin-right:15px;">
        <tbody>
            <tr>
                <td style="width:900px; vertical-align:top;">
                    <h3>
                    	<a href="https://www.unical.it/portale/">
							<img src="{% static 'icons/logo_unical.png' %}" width="312" title="Logo Unical" alt="Logo Unical" style="margin-left:15px;">
                        </a>
					</h3>
                </td>
                <td style="" class="colonna_hp_destra">
                	<br><br><br>
                	<table style="width: 100%; text-align: right;">
                    	<tbody>
                            <tr>
                                <td style="padding-left: 20px;">
                                    <a href="https://www.unical.it/portale/campus/dovesiamo/" class="" title="come raggiungerci">
                                        <img src="{% static 'icons/ico-header-01.png' %}" alt="come raggiungerci" title="come raggiungerci" width="50">
                                    </a>
                                </td>
                                <td style="padding-left: 20px;">
                                    <a href="https://www.unical.it/portale/ateneo/mappe/" class="" target="new" title="Mappe">
                                        <img src="{% static 'icons/ico-header-02.png' %}" alt="Mappe" title="Mappe" width="50">
                                    </a>
                                </td>
                                <td style="padding-left: 20px;">
                                    <a href="https://www.unical.it/portale/portaltemplates/view/search_phone.cfm" class="" title="Contatti">
                                        <img src="{% static 'icons/ico-header-04.png' %}" alt="Contatti" title="Contatti" width="50">
                                    </a>
                                </td>          
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
</div>

unical_template/templates/top_nav.html
{% load static %}
    <nav class=" sfondo_bordeaux">
    	<div class="container">
            <div class="row clearfix">
                <div class="col-xs-12">
                    <ul class="elementi_menu" style="margin-top:-5px;">
                        <li style="padding-top:5px;">
                                {% now "j F Y H:i" %}
                        </li>
                        <li>&nbsp;</li>
                        <li style="background-color:#ECEBE4; height:40px; padding: 0px 2px 0px 2px; width:0px; margin-top:0px;">
                            &nbsp;
                        </li>
                        <li>&nbsp;</li>
<!--
                        <li>
                            <a href="https://www.youtube.com/channel/UCnd5Oen95TMO9aLfVRUAABQ">
                                <img src="{% static 'icons/youtube-icon.png' %}" width="22" alt="Youtube">
                            </a>
                        </li>
                        <li>
                            <a href="https://it-it.facebook.com/pages/Universit%C3%A0-della-Calabria/166678814380">
                                <img src="{% static 'icons/facebook-icon.png' %}" width="22" alt="Facebook">
                            </a>
                        </li>
                        <li>
                            <a href="https://twitter.com/UnicalPortale">
                                <img src="{% static 'icons/twitter-icon.png' %}" width="22" alt="Twitter">
                            </a>
                        </li>
-->
                        <li>&nbsp;</li>
                        <li style="background-color:#ECEBE4; height:40px; padding: 0px 2px 0px 2px; width:0px; margin-top:0px;">
                            &nbsp;
                        </li>
                        <li>&nbsp;</li>
<!--
                        <li style="padding-top:5px;">
                            <a href="http://www.unicaladmission.it/" title="english version" target="_blank">

                                english version
                                <img src="{% static 'icons/flag_en.png' %}" alt="RSS Feed">

                            </a>
                        </li>
-->
                        <li>&nbsp;</li>
                        <li style="background-color:#ECEBE4; height:40px; padding: 0px 2px 0px 2px; width:0px; margin-top:0px;">
                            &nbsp;
                        </li>
                        <li>
<!--
                            <form class="navbar-form navbar-left" style="margin-top:0px; margin-right:-15px; padding-top:0px;" action="https://www.unical.it/portale/search_results.cfm">
                                <div class="form-group">
                                    <input name="search" class="form-control" type="text" placeholder="cerca" style=" border-radius:0px;">
                                </div>
                            </form>
-->
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

unical_template/templates/top_notify_peo.html
{% block top_notify %}

<div class="ui middle aligned divided list success message">
  <div class="item ">
    <div class="right floated content">
      <button class="positive ui button">
			  <i class="plus icon"></i>
			  Partecipa a PEO 2018
		</button>
    </div>
    <div class="content">
      <div class="header">
    Puoi partecipare al nuovo bando PEO.
  </div>
  <p>
	  Sulla base della tua ultima progressione/presa di servizio risulti idoneo a partecipare
  </p>
    </div>
  </div>
  </div>
  
  
  <div class="ui middle aligned divided list warning message">
  <div class="item ">
    <div class="content">
      <div class="header">
    Non puoi partecipare al nuovo bando PEO.
  </div>
  <p>
	  Non sono decorsi i termini minimi dalla tua ultima progressione. Alla prossima!
  </p>
    </div>
  </div>
  </div>

<div class="ui info message">
  <div class="header">
    Tutte le informazioni sul Bando PEO 2018!
  </div>
  <ul class="list">
    <li> Scadenza presentazione domande al </li>
    <li> <a href="#">Modalità di compilazione della domanda</a> </li>
    <li> <a href="#">Scarica il bando completo</a> </li>
  </ul>
</div>
{% endblock %}

unical_template/templates/utente_non_valido.html
{% extends "base.html" %}

{% block content %}
    <h2 class="ui error">Errore di Riconoscimento</h2>

    <h4>Il tuo utente non è stato riconosciuto come un dipendente abilitato.</h4>

    <p>Parrebbe che dagli attributi acquisiti dal Gestore delle Identità di Ateneo (IDP) manchi uno tra i seguenti:</p>

    <div class="ui bulleted list">
        <div class="item">
            Nome
        </div>
        <div class="item">
            Cognome
        </div>
    </div>

    <div>
    Oppure che la tua Matricola non risulti nel Database CSA dei dipendenti strutturati e abilitati ad accedere a questo servizio.
    <br>
    Contatta l'Area Risorse Umane fornendo <i>accuratamente</i> le seguenti informazioni, potrebbero tornare utili per una verifica del tuo stato all'interno del Database CINECA CSA:
    </div>

    <div class="ui card">
        <div class="content">
          Nome, Cognome, <b>Matricola</b>
        </div>
        <div class="content">
          <b>Username</b> utilizzato per accedere al sistema. Attualmente risulti autenticato come:

            <div class="ui bulleted list">
                <div class="item">
                    Nome: <b>{{ request.user.first_name|default_if_none:"Nessun nome rilevato." }}</b>
                </div>
                <div class="item">
                    Cognome: <b>{{ request.user.last_name|default_if_none:"Nessun cognome rilevato." }}</b>
                </div>
                <div class="item">
                    Matricola: <b>{{ request.user.matricola|default_if_none:"Nessuna matricola rilevata." }}</b>
                </div>
            </div>

        </div>
        <div class="content">
          Stato contrattuale: <br><b>Se in servizio o meno e che genere di contratto.</b>
        </div>
        <div class="content">
          Data e orario dell'accesso
        </div>
    </div>

{% endblock %}