django_peo/urls.py
import logging

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path, re_path

from unical_template.views import *

logger = logging.getLogger(__name__)

# admin labels
admin.site.site_header = 'Amministrazione'
admin.site.pretitle    = 'pretitle in urls.py'
admin.site.site_title  = 'Pannello di amministrazione'

urlpatterns = [
    path('gestione/', admin.site.urls),
    path('logout/', logout_view, name='logout'),
    path('500/', test_500, name='test_500'),
    path('timeout/<seconds>', test_timeout, name='test_timeout'),
]

handler500 = error_500

if settings.DEBUG:
    # STATICS FILE SERVE
    from django.views.static import serve
    urlpatterns.append(
        path('{}/<path>'.format(settings.STATIC_URL[1:-1]),
            serve,
            {'document_root': settings.STATIC_ROOT,
             'show_indexes' : True})
    )
    # MEDIA FILE SERVE
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    # protected download in production environment
    urlpatterns.append(
        # [1:] avoids: (urls.W002) Your URL pattern '/media//<path>' has a route beginning with a '/'
        re_path('{}/(?P<path>[a-zA-Z0-9\_\-\.1\/]+)'.format(settings.MEDIA_URL[1:-1]),
                protected_serve, name='protected_download')
    )
    urlpatterns.append(
        # [1:] avoids: (urls.W002) Your URL pattern '/media//<path>' has a route beginning with a '/'
        re_path('{}{}/(?P<path>[a-zA-Z0-9\_\-\.1\/]+)'.format(settings.HOSTNAME,
                                                              settings.MEDIA_URL[1:-1]),
                protected_serve, name='protected_download')
    )


if 'adminactions' in settings.INSTALLED_APPS:
    from django.contrib.admin import site
    import adminactions.actions as actions
    import adminactions.urls
    urlpatterns += path('adminactions/', include((adminactions.urls, 'adminactions'))),
    actions.add_to_site(site)

if 'advanced_filters' in settings.INSTALLED_APPS:
    import advanced_filters.urls
    urlpatterns += path('advanced_filters/', include((advanced_filters.urls, 'advanced_filters'))),

# Esempio di come includere gli urls delle app solo se queste sono installate
if 'nested_admin' in settings.INSTALLED_APPS:
    import nested_admin.views
    urlpatterns += path('server-data\.js', nested_admin.views.server_data_js,
                        name="nesting_server_data"),

if 'unical_template' in settings.INSTALLED_APPS:
    import unical_template.urls
    urlpatterns += path('template/', include(unical_template.urls, namespace='unical_template')),

if 'gestione_risorse_umane' in settings.INSTALLED_APPS:
    import gestione_risorse_umane.urls
    urlpatterns += path('', include(gestione_risorse_umane.urls, namespace='risorse_umane')),

if 'gestione_peo' in settings.INSTALLED_APPS:
    import gestione_peo.urls
    urlpatterns += path('', include(gestione_peo.urls, namespace='gestione_peo')),

if 'domande_peo' in settings.INSTALLED_APPS:
    import domande_peo.urls
    urlpatterns += path('', include(domande_peo.urls, namespace='domande_peo')),

if 'saml2_sp' in settings.INSTALLED_APPS:
    import saml2_sp.urls
    urlpatterns += path('', include((saml2_sp.urls, 'sp',))),

domande_peo/urls.py
from django.urls import path
from wkhtmltopdf.views import PDFTemplateView

from .views import *

app_name="domande_peo"

urlpatterns = [
    path('bando/<str:bando_id>/domanda/aggiungi/<int:descrizione_indicatore_id>/',
         aggiungi_titolo, name='aggiungi_titolo'),

    path('bando/<str:bando_id>/domanda/modifica/<int:modulo_compilato_id>/',
          modifica_titolo, name='modifica_titolo'),

    path('bando/<str:bando_id>/cancella/domanda/<int:domanda_bando_id>/',
          cancella_domanda, name='cancella_domanda'),

    path('bando/<str:bando_id>/domanda/cancella/modulo/<int:modulo_compilato_id>/',
          cancella_titolo, name='cancella_titolo'),

    path('bando/<str:bando_id>/domanda/',
         dashboard_domanda, name='dashboard_domanda'),
         
    path('bando/<str:bando_id>/domanda/aggiungi',
         scelta_titolo_da_aggiungere, name='scelta_titolo_da_aggiungere'),
        
    path('bando/<int:bando_id>/anteprima/<int:descrizione_indicatore_id>/',
         anteprima_modulo_inserimento, name='anteprima_modulo_inserimento'),
        
    path('bando/<int:bando_id>/anteprima-utente/<int:descrizione_indicatore_id>/',
         anteprima_modulo_inserimento_frontend, name='anteprima_modulo_inserimento_frontend'),

    path('bando/<str:bando_id>/vedi/<int:modulo_domanda_bando_id>/',
         vedi_modulo_inserito, name='vedi_modulo_inserito'),
    
    path('bando/<str:bando_id>/accetta-condizioni/',
         accetta_condizioni_bando, name='accetta_condizioni_bando'), 
         
    path('bando/<str:bando_id>/modifica/<int:modulo_compilato_id>/elimina_allegato/<str:allegato>/',
         elimina_allegato, name='elimina_allegato'), 
         
    path('bando/<str:bando_id>/<int:modulo_compilato_id>/download_allegato/<str:allegato>/',
         download_allegato, name='download_allegato'), 
         
    #path('bando/<str:bando_id>/riepilogo_domanda/<int:domanda_bando_id>/',
    #     PDFTemplateView.as_view(template_name='top_notify.html',
    #                             filename='riepilogo.pdf'), 
    #     name='riepilogo_domanda_pdf'),
    
    path('bando/<str:bando_id>/domanda/riepilogo/<int:domanda_bando_id>/',
          riepilogo_domanda, name='riepilogo_domanda'), 

    path('bando/<str:bando_id>/<int:modulo_compilato_id>/download_pdf',
          download_modulo_inserito_pdf, name='download_modulo_inserito_pdf'),

    path('bando/<str:bando_id>/riepilogo_domanda/<int:domanda_bando_id>/download_pdf',
          download_domanda_pdf, name='download_domanda_pdf'),

    path('bando/<str:bando_id>/domanda/<int:domanda_bando_id>/<str:azione>/',
          chiudi_apri_domanda, name='chiudi_apri_domanda'),

]

gestione_peo/urls.py
from django.urls import path
from .views import *

app_name="gestione_peo"

urlpatterns = [
    path('bandi/<str:bando_id>/', dettaglio_bando_peo, name='dettaglio_bando_peo'),
    path('bandi', bandi_peo, name='bandi_peo'),
    path('bandi/import_file', import_file, name='import_file'),
    path('bandi/<str:bando_id>/avvisi/<int:avviso_id>/download/', download_avviso, name='download_avviso'),

    # Commissione bando
    path('commissioni', commissioni, name='commissioni'),
    path('commissioni/<int:commissione_id>/', commissione_dettaglio, name='dettaglio_commissione'),
    path('commissioni/<int:commissione_id>/gestisci', commissione_manage, name='manage_commissione'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>', commissione_domanda_manage, name='commissione_domanda_manage'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/extended', commissione_domanda_manage_extended, name='commissione_domanda_manage_extended'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/download_allegato/<str:allegato>/',commissione_download_allegato, name='commissione_download_allegato'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/elimina_allegato/<str:allegato>/',commissione_elimina_allegato, name='commissione_elimina_allegato'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/abilita', commissione_abilita_domanda, name='commissione_abilita_domanda'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/disabilita', commissione_disabilita_domanda, name='commissione_disabilita_domanda'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/aggiungi', commissione_domanda_scegli_titolo, name='commissione_domanda_scegli_titolo'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/aggiungi/<int:descrizione_indicatore_id>', commissione_domanda_aggiungi_titolo, name='commissione_domanda_aggiungi_titolo'),

    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/duplica', commissione_domanda_duplica_titolo, name='commissione_domanda_duplica_titolo'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/duplica/<int:descrizione_indicatore_id>', commissione_domanda_duplica_titolo_confirm, name='commissione_domanda_duplica_titolo_confirm'),

    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/modifica', commissione_modulo_domanda_modifica, name='commissione_modulo_domanda_modifica'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/cancella', commissione_cancella_titolo, name='commissione_cancella_titolo'),
]

gestione_risorse_umane/urls.py
from django.urls import path
from .views import *

app_name="risorse_umane"

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('aggiorna_carta_identita', upload_carta_identita, name='upload_carta_identita'),
]

saml2_sp/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import logout

from . import views

urlpatterns = [
    path('', views.index),
    path('logout/', logout),
    path('saml2/', include('djangosaml2.urls')),
]

gestione_risorse_umane/forms.py
from django import forms
from django.conf import settings
from django.contrib.admin.widgets import AdminDateWidget
from django.forms.fields import DateField
from django.template.defaultfilters import filesizeformat

from .models import *

class CartaIdentitaForm(forms.Form):
    carta_identita_front = forms.FileField(label='Fronte')
    carta_identita_retro = forms.FileField(label='Retro')

    def clean(self):
        cleaned_data = super().clean()
        for field_name in ('carta_identita_front', 'carta_identita_retro'):
            content = self.cleaned_data.get(field_name)
            # rimuovere caratteri di encoding altrimenti il download fallisce lato ws
            if not content:
                msg = "E' incorso un errore in uno dei due file caricati, prego reinserire i files"
                self.add_error(field_name, msg)
                return
            content._name = content._name.encode('ascii', errors='ignore').decode('ascii')

            if content.content_type not in settings.IMG_PERMITTED_UPLOAD_FILETYPE:
                msg_tmpl = "Per favore esegui l'upload di soli file nel seguente formato: '{}'"
                msg = msg_tmpl.format(', '.join(settings.IMG_PERMITTED_UPLOAD_FILETYPE))
                self.add_error(field_name, msg)
            elif content.size > int(settings.IMG_MAX_UPLOAD_SIZE):
                msg_tmpl = "Per favore mantieni la dimensione del file entro {}. {} è {}"
                msg = msg_tmpl.format(filesizeformat(settings.MAX_UPLOAD_SIZE),
                                      content._name,
                                      filesizeformat(content.size))
                self.add_error(field_name, msg)
            elif len(content._name) > settings.ATTACH_NAME_MAX_LEN:
                msg_tmpl = ("Per favore usa una lunghezza massima "
                            "dell'allegato inferiore a {}. Attualmente questa è {}")
                msg = msg_tmpl.format(settings.ATTACH_NAME_MAX_LEN,
                                      len(content._name))
                self.add_error(field_name, msg)

gestione_risorse_umane/views.py
import logging

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render

from gestione_peo.models import *
from gestione_peo.utils import get_commissioni_attive, get_commissioni_in_corso
from gestione_risorse_umane.models import Dipendente, Avviso
from unical_template.decorators import site_not_in_manteinance
from unical_template.breadcrumbs import BreadCrumbs

from .forms import *
#from .decorators import matricola_in_csa


logger = logging.getLogger(__name__)


@site_not_in_manteinance
@login_required
#@matricola_in_csa
def dashboard(request):
    """ landing page """

    commissioni_attive = get_commissioni_attive(request.user)
    commissioni_in_corso = get_commissioni_in_corso(request.user,commissioni_attive)

    dipendente = Dipendente.objects.filter(matricola=request.user.matricola).first()
    # creazione dipendente in gestione_risorse_umane se questo non esiste
    if not dipendente:
        dipendente = Dipendente.objects.create(matricola=request.user.matricola,
                                               nome = request.user.first_name,
                                               cognome = request.user.last_name,
                                               utente=request.user)
        dipendente.sync_csa()
    if not dipendente.utente:
        dipendente.utente = request.user
        dipendente.save()

    if dipendente.utente.is_staff:
        bandi = dipendente.idoneita_peo_staff()
    elif dipendente.idoneita_peo_attivata():
        bandi = dipendente.idoneita_peo_attivata()
    else:
        bandi = Bando.objects.none()

    # Escludi i bandi scaduti!
    excluded_pk=[]
    for bando in bandi:
       if not bando.is_in_corso():
           excluded_pk.append(bando.pk)
    bandi = bandi.exclude(pk__in=excluded_pk)

    domande_bando = dipendente.get_domande_progressione()
    for dom in domande_bando:
        for ban in bandi:
            if dom.bando == ban:
                ban.iniziato_dipendente = True

    # dipendente.sync_csa()
    # n = reverse('domande_peo:accetta_condizioni_bando',
                # args=[bandi.first().pk])
    # _logger.error(n)

    d = {
        'commissioni': commissioni_attive,
        'commissioni_in_corso': commissioni_in_corso,
        'dipendente': dipendente,
        'domande_bando': domande_bando,
        'bandi': bandi,
        'MEDIA_URL': settings.MEDIA_URL,
        'avvisi': Avviso.objects.filter(is_active=1),
        }
    return render(request, "dashboard.html", context=d)


@login_required
def upload_carta_identita(request):
    """
        Primo upload o aggiornamento carta identità dipendente
    """
    dipendente = Dipendente.objects.filter(matricola=request.user.matricola).first()

    if request.method == 'POST':
        form = CartaIdentitaForm(request.POST, request.FILES)
        if form.is_valid():
            dipendente.carta_identita_front = request.FILES['carta_identita_front']
            dipendente.carta_identita_retro = request.FILES['carta_identita_retro']
            dipendente.save()
            return HttpResponseRedirect('/')
    else:
        form = CartaIdentitaForm()

    page_title = 'Gestione documento di identità'
    d = {
        'page_title': page_title,
        'breadcrumbs': BreadCrumbs(url_list=(('#', page_title),)),
        'form':form,
        'dipendente': dipendente,
        'MEDIA_URL': settings.MEDIA_URL,
        'IMAGE_TYPES': ', '.join([i.split('/')[1] for i in settings.IMG_PERMITTED_UPLOAD_FILETYPE]),
        'IMAGE_MAX_SIZE': '{} MB.'.format(int(settings.IMG_MAX_UPLOAD_SIZE / (1024.)**2)),
        }
    return render(request, 'upload_carta_identita.html', d)

gestione_risorse_umane/templates/carta_identita_dialog.html
{% load static %}

<div class="image card" id="carta_identita">
    {% if dipendente.carta_identita_front and dipendente.carta_identita_retro  %}
    <div class="front">
        <a href="{% url 'risorse_umane:upload_carta_identita' %}">
            <img class="ui fluid image" src="{{ MEDIA_URL }}/{{ dipendente.carta_identita_front }}">
        </a>
    </div>
    <div class="back">
        <a href="{% url 'risorse_umane:upload_carta_identita' %}">
            <img class="ui fluid image" src="{{ MEDIA_URL }}/{{ dipendente.carta_identita_retro }}">
        </a>
    </div>
    {% else %}
    <!-- CI Template backfault -->
    <div class="front">
        <a href="{% url 'risorse_umane:upload_carta_identita' %}">
            <img class="ui fluid image" src="{% static 'images/ci_fronte.jpg' %}">
        </a>
    </div>
    <div class="back">
        <a href="{% url 'risorse_umane:upload_carta_identita' %}">
            <img class="ui fluid image" src="{% static 'images/ci_retro.jpg' %}">
        </a>
    </div>
    {% endif %}

    <div style="width:100%;text-align: center; margin-top: 10px;">
        <div class="ui small buttons">
            <button class="left attached ui button" id="retro">Fronte</button>
            <button class="ui right attached button" id="fronte">Retro</button>
        </div>
    </div>
</div>

gestione_risorse_umane/templates/commissioni_utente.html
{% if commissioni %}
<div class="ui horizontal divider"></div>
<h3 class="ui dividing header item">Commissioni di cui faccio parte</h3>
<p>
    In questa sezione puoi visionare tutte le commissioni di cui hai fatto parte..........
</p>
<div class="ui fluid styled accordion">
    {% for commissione in commissioni %}
        {% with commissione.is_in_corso as commissione_in_corso %}
        <div class="title" style="color: #000000;">
            <i class="dropdown icon"></i> {{ commissione }}
        </div>
        <div class="ui content">
            <div class="ui list">
                <div class="item">
                    <i class="file alternate outline icon"></i>
                    <div class="content">
                        <b>Bando:</b>
                        <a href="{% url 'gestione_peo:dettaglio_bando_peo' bando_id=commissione.bando.slug %}">
                            {{ commissione.bando }}
                        </a>
                    </div>
                </div>
                <div class="item">
                    <i class="calendar alternate outline icon"></i>
                    <div class="content">
                        <b>Data inizio:</b> {{ commissione.data_inizio }}
                        <br>
                        <b>Data fine:</b> {{ commissione.data_fine }}
                    </div>
                </div>
                <div class="item">
                     <i class="hourglass start icon"></i>
                    <div class="content">
                        <b>Stato:</b>
                        {% if commissione_in_corso %}
                            <span style="color:green">In Corso</span>
                        {% elif commissione.is_terminata %}
                            <span style="color:blue">Commissione non più accessibile</span>
                        {% else %}
                            <span style="color:red">Commissione non ancora attiva</span>
                        {% endif %}
                    </div>
                </div>

                {% if commissione_in_corso %}
                <div class="item" style="margin-top: 21px;">
                    <a href="{% url 'gestione_peo:dettaglio_commissione' commissione_id=commissione.pk %}">
                        <button class="ui left floated labeled icon blue button">
                            <i class="file outline icon"></i>
                            Accedi ai dettagli della Commissione
                        </button>
                    </a>
                    <a href="{% url 'gestione_peo:manage_commissione' commissione_id=commissione.pk %}">
                        <button class="ui right floated positive button">
                            <i class="file alternate outline icon"></i>
                            Gestisci le domande del bando "{{ commissione.bando }}"
                        </button>
                    </a>
                </div>
                {% endif %}
            </div>
        </div>
        {% endwith %}
    <!--
    domanda_bando in domande_bando
    -->
    {% endfor %}
</div>

{% endif %}

gestione_risorse_umane/templates/dati_personali.html
<ol class="ui list">
    <li value="*">Matricola: <b>{{ dipendente.matricola }}</b></li>
    <li value="*">
        E-mail: <b>{{ dipendente.utente.email|lower|default_if_none:"Nessuna e-mail presente" }}</b>
    </li>
    {% comment %}
    <li value="*">Sede: {{ dipendente.sede }}</li>
    <li value="*">In servizio presso: {{ dipendente.afferenza_organizzativa }}</li>
    <li value="*">Posizione economica: <b>{{ dipendente.livello }}</b></li>
    <li value="*">Categoria: <b>{{ dipendente.profilo }}</b></li>

        {% if dipendente.data_cessazione_contratto %}
        al {{dipendente.data_cessazione_contratto|date:"j F Y"}}
        {% endif %}

    {% endcomment %}

    {% comment %}
    <li value="*">
        In servizio dal: {{dipendente.data_presa_servizio|date:"j F Y"}}
        ({{ dipendente.get_anzianita_repr }}) come {{ dipendente.ruolo }}
    </li>
    {% with dipendente.get_data_progressione as data_progressione %}
    {% if data_progressione %}
        <li value="*">
            Ultima progressione: {{ data_progressione }}
        </li>
    {% endif %}
    {% endwith %}
    {% endcomment %}
</ol>

gestione_risorse_umane/templates/right_main_menu.html
<div class="ui sticky">
    <div class="ui fluid vertical menu">
        {% if bandi %}
        <div class="item">
            <div class="header">Bandi/Avvisi attivi</div>
            {% for bando in bandi %}
            <div class="menu">
                <a class="active item green">
                    {{ bando }}
                </a>
                <a class="item" href="{% url 'gestione_peo:dettaglio_bando_peo' bando_id=bando.slug %}">
                    Descrizione
                </a>
                {% if bando.bando_url %}
                <a class="item"  href="{{ bando.bando_url }}">
                    Vai alle risorse online
                </a>
                {% endif %}
            </div>
            {% endfor %}
        </div>
        {% endif %}

        <div class="item">
            <div class="header">Tutti i Bandi/Avvisi</div>
            <div class="menu">
                <a class="item" href="{% url 'gestione_peo:bandi_peo' %}">
                    Vedi lista
                </a>
            </div>
        </div>

        {% if commissioni_in_corso %}
        <div class="item">
            <div class="header">Commissioni attive</div>
            {% for commissione in commissioni_in_corso %}
            <div class="menu">
                <a class="active item green">
                    {{ commissione }}
                </a>
                <a class="item" href="{% url 'gestione_peo:dettaglio_commissione' commissione_id=commissione.pk %}">
                    Dettagli
                </a>
                <a class="item"  href="{% url 'gestione_peo:manage_commissione' commissione_id=commissione.pk %}">
                    Gestione domande
                </a>
            </div>
            {% endfor %}
        </div>
        {% endif %}

        {% if commissioni %}
        <div class="item">
            <div class="header">Le mie commissioni</div>
            <div class="menu">
                <a class="item" href="{% url 'gestione_peo:commissioni' %}">
                    Vedi lista
                </a>
            </div>
        </div>
        {% endif %}

        <div class="item">
            <div class="header">Account</div>
            <div class="menu">
                <a class="item" href="/">
                    Pagina principale
                </a>

                <a class="item" href="{% url 'risorse_umane:upload_carta_identita' %}">
                    Modifica Documento di identità
                </a>

                {% if request.user.is_superadministrator or request.user.is_staff %}
                <a class="active item green" href="{% url 'admin:index' %}">
                    Gestione avanzata
                </a>
                {% endif %}

                <a class="item" href="{% url 'logout' %}?next={{ request.path }}">
                    Logout / Esci
                </a>
            </div>

        </div>
        <div class="item">
            <div class="header">Link utili</div>
            <div class="menu">
                <a class="item" href="http://www.unical.it/portale/ateneo/amministrazione/aree/arrisumane/">Area Risorse Umane</a>
            </div>
        </div>
        <div class="item">
            <div class="header">Supporto Tecnico</div>
            <div class="menu">
                <a class="item" href="mailto:supporto.peo@unical.it" >Scrivi a supporto.peo@unical.it</a>
            </div>
        </div>
        <div class="item">
            <div class="header">Documentazione</div>
            <div class="menu">
                <a class="item" href="/docs">Guida all'utilizzo</a>
            </div>
        </div>
    </div>
</div>
{% block bottom_scripts %}
<script>
    $('.ui.sticky')
            .sticky({
                context: '#sticky_reference_panel'
            })
            ;
</script>
{% endblock %}

gestione_risorse_umane/templates/storico_domande.html
{% if domande_bando %}
    <div class="ui horizontal divider"></div>
    <h3 class="ui dividing header item">Storico delle Domande e Aggiornamenti</h3>
    <p>
        In questa sezione puoi visionare tutte le domande relative
        ai precedenti bandi/avvisi ai quali hai partecipato attraverso questa piattaforma.
    </p>
    <div class="ui fluid styled accordion">

        {% for domanda_bando in domande_bando %}
            {% with domanda_bando.is_protocollata as domanda_protocollata %}
            <div class="title" style="color: #000000;">
                <i class="dropdown icon"></i> {{ domanda_bando.bando.nome}}
            </div>
            <div class="ui content" style="padding: 3%;">
                <div class="ui list">
                    <div class="item">
                        <i class="file alternate outline icon"></i>
                        <div class="content">
                            <b>Parametri:</b>
                            <a href="{% url 'gestione_peo:dettaglio_bando_peo' bando_id=domanda_bando.bando.slug %}">
                                Consulta
                            </a>
                        </div>
                    </div>

                    {% with domanda_bando.bando.avvisobando_set.all as avvisi_bando %}
                    {% if avvisi_bando %}
                        {% for avviso_bando in avvisi_bando %}
                            {% if avviso_bando.is_active %}
                            <div class="item">
                                <i class="envelope outline icon"></i>
                                <div class="content">
                                    <b>{{ avviso_bando.titolo }}</b> ({{ avviso_bando.created }}):
                                    <a style="color: #4183c4;"  href="{% url 'gestione_peo:download_avviso' bando_id=domanda_bando.bando.slug avviso_id=avviso_bando.pk %}">
                                        Consulta
                                    </a>
                                </div>
                            </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    {% endwith %}

                    <div class="ui divider"></div>

                    {% if domanda_protocollata %}
                        <div class="item">
                            <i class="calendar icon"></i>
                            <div class="content">
                                {% if domanda_bando.progressione_accettata %}
                                    <b style="color:green">PROGRESSIONE ACCETTATA</b>
                                {% else %}
                                    <b>--</b>
                                {% endif %}
                            </div>
                        </div>
                    {% endif %}

                    <div class="item">
                        <i class="calendar alternate outline icon"></i>
                        <div class="content">
                            <b>Data creazione:</b> {{domanda_bando.created}}
                        </div>
                    </div>
                    <div class="item">

                        {% if domanda_bando.bando.is_in_corso %}
                            <i class="hourglass start icon"></i>
                            <div class="content">
                                <b>Stato:</b>
                                <span style="color:green">In Corso</span>
                            </div>

                        {% elif domanda_protocollata %}
                            <i class="hourglass end icon"></i>
                            <div class="content">
                                <b>Stato:</b>
                                <span>
                                    Chiusa e Protocollata ({{ domanda_bando.data_protocollazione }})
                                </span>
                            </div>

                        {% else %}
                            <i class="hourglass half icon"></i>
                            <div class="content">
                                <b>Stato:</b>
                                <span style="color:red">Chiusa</span>
                            </div>
                        {% endif %}

                    </div>
                    <div class="item" style="margin-top: 21px;">
                        <a href="{% url 'domande_peo:riepilogo_domanda' bando_id=domanda_bando.bando.pk domanda_bando_id=domanda_bando.pk  %}">
                            <button class="ui left floated labeled icon blue button">
                                <i class="file pdf outline icon"></i> Riepilogo stampabile
                            </button>
                        </a>
                        <a href="{% url 'domande_peo:accetta_condizioni_bando' bando_id=domanda_bando.bando.slug %}">
                            <button class="ui right floated positive button">
                                <i class="file alternate outline icon"></i> Accedi alla tua Domanda di partecipazione
                            </button>
                        </a>
                    </div>
                </div>
            </div>
            {% endwith %}
        <!--
        domanda_bando in domande_bando
        -->
        {% endfor %}
    </div>
    <!--
end if domande_bando
-->
{% endif %}

gestione_risorse_umane/templates/top_notify.html
{% block top_notify %}

{% if not dipendente.carta_identita_front or not dipendente.carta_identita_retro  %}
<div class="ui error message">
    <div class="ui grid">
        <div class="thirteen wide column">
            <div class="header">
                Carta di Identità mancante
            </div>
            <p>
                Senza aver registrato la tua Carta di Identità non è
                possibile utilizzare i servizi offerti dalla piattaforma
            </p>
        </div>
        <div class="three wide column">
            <a href="{% url 'risorse_umane:upload_carta_identita' %}">
                <button class="ui negative button">Esegui ora l'upload</button>
            </a>
        </div>
    </div>
</div>
{% endif  %}

{% endblock %}