django_peo/urls.py
import logging

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path, re_path

from unical_template.views import *

logger = logging.getLogger(__name__)

# admin labels
admin.site.site_header = 'Amministrazione'
admin.site.pretitle    = 'pretitle in urls.py'
admin.site.site_title  = 'Pannello di amministrazione'

urlpatterns = [
    path('gestione/', admin.site.urls),
    path('logout/', logout_view, name='logout'),
    path('500/', test_500, name='test_500'),
    path('timeout/<seconds>', test_timeout, name='test_timeout'),
]

handler500 = error_500

if settings.DEBUG:
    # STATICS FILE SERVE
    from django.views.static import serve
    urlpatterns.append(
        path('{}/<path>'.format(settings.STATIC_URL[1:-1]),
            serve,
            {'document_root': settings.STATIC_ROOT,
             'show_indexes' : True})
    )
    # MEDIA FILE SERVE
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    # protected download in production environment
    urlpatterns.append(
        # [1:] avoids: (urls.W002) Your URL pattern '/media//<path>' has a route beginning with a '/'
        re_path('{}/(?P<path>[a-zA-Z0-9\_\-\.1\/]+)'.format(settings.MEDIA_URL[1:-1]),
                protected_serve, name='protected_download')
    )
    urlpatterns.append(
        # [1:] avoids: (urls.W002) Your URL pattern '/media//<path>' has a route beginning with a '/'
        re_path('{}{}/(?P<path>[a-zA-Z0-9\_\-\.1\/]+)'.format(settings.HOSTNAME,
                                                              settings.MEDIA_URL[1:-1]),
                protected_serve, name='protected_download')
    )


if 'adminactions' in settings.INSTALLED_APPS:
    from django.contrib.admin import site
    import adminactions.actions as actions
    import adminactions.urls
    urlpatterns += path('adminactions/', include((adminactions.urls, 'adminactions'))),
    actions.add_to_site(site)

if 'advanced_filters' in settings.INSTALLED_APPS:
    import advanced_filters.urls
    urlpatterns += path('advanced_filters/', include((advanced_filters.urls, 'advanced_filters'))),

# Esempio di come includere gli urls delle app solo se queste sono installate
if 'nested_admin' in settings.INSTALLED_APPS:
    import nested_admin.views
    urlpatterns += path('server-data\.js', nested_admin.views.server_data_js,
                        name="nesting_server_data"),

if 'unical_template' in settings.INSTALLED_APPS:
    import unical_template.urls
    urlpatterns += path('template/', include(unical_template.urls, namespace='unical_template')),

if 'gestione_risorse_umane' in settings.INSTALLED_APPS:
    import gestione_risorse_umane.urls
    urlpatterns += path('', include(gestione_risorse_umane.urls, namespace='risorse_umane')),

if 'gestione_peo' in settings.INSTALLED_APPS:
    import gestione_peo.urls
    urlpatterns += path('', include(gestione_peo.urls, namespace='gestione_peo')),

if 'domande_peo' in settings.INSTALLED_APPS:
    import domande_peo.urls
    urlpatterns += path('', include(domande_peo.urls, namespace='domande_peo')),

if 'saml2_sp' in settings.INSTALLED_APPS:
    import saml2_sp.urls
    urlpatterns += path('', include((saml2_sp.urls, 'sp',))),

domande_peo/urls.py
from django.urls import path
from wkhtmltopdf.views import PDFTemplateView

from .views import *

app_name="domande_peo"

urlpatterns = [
    path('bando/<str:bando_id>/domanda/aggiungi/<int:descrizione_indicatore_id>/',
         aggiungi_titolo, name='aggiungi_titolo'),

    path('bando/<str:bando_id>/domanda/modifica/<int:modulo_compilato_id>/',
          modifica_titolo, name='modifica_titolo'),

    path('bando/<str:bando_id>/cancella/domanda/<int:domanda_bando_id>/',
          cancella_domanda, name='cancella_domanda'),

    path('bando/<str:bando_id>/domanda/cancella/modulo/<int:modulo_compilato_id>/',
          cancella_titolo, name='cancella_titolo'),

    path('bando/<str:bando_id>/domanda/',
         dashboard_domanda, name='dashboard_domanda'),
         
    path('bando/<str:bando_id>/domanda/aggiungi',
         scelta_titolo_da_aggiungere, name='scelta_titolo_da_aggiungere'),
        
    path('bando/<int:bando_id>/anteprima/<int:descrizione_indicatore_id>/',
         anteprima_modulo_inserimento, name='anteprima_modulo_inserimento'),
        
    path('bando/<int:bando_id>/anteprima-utente/<int:descrizione_indicatore_id>/',
         anteprima_modulo_inserimento_frontend, name='anteprima_modulo_inserimento_frontend'),

    path('bando/<str:bando_id>/vedi/<int:modulo_domanda_bando_id>/',
         vedi_modulo_inserito, name='vedi_modulo_inserito'),
    
    path('bando/<str:bando_id>/accetta-condizioni/',
         accetta_condizioni_bando, name='accetta_condizioni_bando'), 
         
    path('bando/<str:bando_id>/modifica/<int:modulo_compilato_id>/elimina_allegato/<str:allegato>/',
         elimina_allegato, name='elimina_allegato'), 
         
    path('bando/<str:bando_id>/<int:modulo_compilato_id>/download_allegato/<str:allegato>/',
         download_allegato, name='download_allegato'), 
         
    #path('bando/<str:bando_id>/riepilogo_domanda/<int:domanda_bando_id>/',
    #     PDFTemplateView.as_view(template_name='top_notify.html',
    #                             filename='riepilogo.pdf'), 
    #     name='riepilogo_domanda_pdf'),
    
    path('bando/<str:bando_id>/domanda/riepilogo/<int:domanda_bando_id>/',
          riepilogo_domanda, name='riepilogo_domanda'), 

    path('bando/<str:bando_id>/<int:modulo_compilato_id>/download_pdf',
          download_modulo_inserito_pdf, name='download_modulo_inserito_pdf'),

    path('bando/<str:bando_id>/riepilogo_domanda/<int:domanda_bando_id>/download_pdf',
          download_domanda_pdf, name='download_domanda_pdf'),

    path('bando/<str:bando_id>/domanda/<int:domanda_bando_id>/<str:azione>/',
          chiudi_apri_domanda, name='chiudi_apri_domanda'),

]

gestione_peo/urls.py
from django.urls import path
from .views import *

app_name="gestione_peo"

urlpatterns = [
    path('bandi/<str:bando_id>/', dettaglio_bando_peo, name='dettaglio_bando_peo'),
    path('bandi', bandi_peo, name='bandi_peo'),
    path('bandi/import_file', import_file, name='import_file'),
    path('bandi/<str:bando_id>/avvisi/<int:avviso_id>/download/', download_avviso, name='download_avviso'),

    # Commissione bando
    path('commissioni', commissioni, name='commissioni'),
    path('commissioni/<int:commissione_id>/', commissione_dettaglio, name='dettaglio_commissione'),
    path('commissioni/<int:commissione_id>/gestisci', commissione_manage, name='manage_commissione'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>', commissione_domanda_manage, name='commissione_domanda_manage'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/extended', commissione_domanda_manage_extended, name='commissione_domanda_manage_extended'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/download_allegato/<str:allegato>/',commissione_download_allegato, name='commissione_download_allegato'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/elimina_allegato/<str:allegato>/',commissione_elimina_allegato, name='commissione_elimina_allegato'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/abilita', commissione_abilita_domanda, name='commissione_abilita_domanda'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/disabilita', commissione_disabilita_domanda, name='commissione_disabilita_domanda'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/aggiungi', commissione_domanda_scegli_titolo, name='commissione_domanda_scegli_titolo'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/aggiungi/<int:descrizione_indicatore_id>', commissione_domanda_aggiungi_titolo, name='commissione_domanda_aggiungi_titolo'),

    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/duplica', commissione_domanda_duplica_titolo, name='commissione_domanda_duplica_titolo'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/duplica/<int:descrizione_indicatore_id>', commissione_domanda_duplica_titolo_confirm, name='commissione_domanda_duplica_titolo_confirm'),

    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/modifica', commissione_modulo_domanda_modifica, name='commissione_modulo_domanda_modifica'),
    path('commissioni/<int:commissione_id>/gestisci/domande/<int:domanda_id>/modulo/<int:modulo_id>/cancella', commissione_cancella_titolo, name='commissione_cancella_titolo'),
]

saml2_sp/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import logout

from . import views

urlpatterns = [
    path('', views.index),
    path('logout/', logout),
    path('saml2/', include('djangosaml2.urls')),
]

unical_template/urls.py
from django.urls import path
from .views import *

app_name="unical_template"

urlpatterns = [
    path('base', base_template, name='base'),
    path('dashboard', dashboard_template, name='dashboard'),
]

gestione_peo/forms.py
import datetime
import magic
import os

from django import forms
from django.conf import settings
from django.forms.fields import FileField
from django.template.defaultfilters import filesizeformat
from django.utils import timezone

from django_form_builder.dynamic_fields import format_field_name
from django_form_builder.forms import BaseDynamicForm

from . import peo_formfields
from . settings import (ETICHETTA_INSERIMENTI_ID,
                        ETICHETTA_INSERIMENTI_LABEL,
                        ETICHETTA_INSERIMENTI_HELP_TEXT)


class PeoDynamicForm(BaseDynamicForm):
    def __init__(self,
                 constructor_dict={},
                 custom_params={},
                 *args,
                 **kwargs):

        self.fields = {}
        self.domanda_bando = custom_params.get('domanda_bando')
        self.descrizione_indicatore = custom_params.get('descrizione_indicatore')

        # Inserimento manuale del field ETICHETTA
        etichetta_id = format_field_name(ETICHETTA_INSERIMENTI_ID)
        etichetta_data = {'required' : True,
                          'label': ETICHETTA_INSERIMENTI_LABEL,
                          'help_text': ETICHETTA_INSERIMENTI_HELP_TEXT}
        etichetta_field = getattr(peo_formfields,
                                  'CustomCharField')(**etichetta_data)
        self.fields[etichetta_id] = etichetta_field
        self.fields[etichetta_id].initial = self.descrizione_indicatore

        super().__init__(fields_source=peo_formfields,
                         initial_fields=self.fields,
                         constructor_dict=constructor_dict,
                         custom_params=custom_params,
                         *args, **kwargs)

    def clean(self, *args, **kwargs):
        super().clean(domanda_bando=self.domanda_bando)

gestione_peo/templates/commissione_buttons_domanda_peo.html
{% if not domanda_bando.bando.presentazione_domande_scaduta and domanda_bando.is_aperta %}
<div class="row " style="margin:20px 0;">
    <a href="{% url 'domande_peo:scelta_titolo_da_aggiungere' bando_id=domanda_bando.bando.slug%}">
        <div class="ui right floated labeled icon positive button">
            <i class="plus circle icon"></i>
            Aggiungi Modulo
        </div>
    </a>
</div>
{% endif %}

<div style="margin:20px 0;">
    {% if not domanda_bando.bando.presentazione_domande_scaduta and domanda_bando.is_aperta and not domanda_bando.descr_ind_non_cancellabili %}
        <div class="ui red button" id="but_cancella_domanda_{{domanda_bando.pk}}">
            <i class="delete icon"></i> Distruggi la tua Domanda
        </div>
    {% endif %}

    <a href="{% url 'domande_peo:riepilogo_domanda' bando_id=domanda_bando.bando.pk domanda_bando_id=domanda_bando.pk  %}">
        <div class="ui button">
            <i class="print icon"></i> Riepilogo
        </div>
    </a>

    {% if not domanda_bando.bando.presentazione_domande_scaduta and domanda_bando.is_aperta %}

        {% if domanda_bando.valida %}
         <div class="ui right floated labeled icon positive button lockbutton" id="but_chiudi_domanda_{{domanda_bando.pk}}">
            <i class="arrow alternate envelope outline icon"></i>
            {% if domanda_bando.bando.protocollo_required %}
                Concludi e Protocolla
            {% else %}
                Concludi
            {% endif %}
        </div>

        {% else %}
        <div class="ui right floated orange button" id="check_chiudi_domanda_{{domanda_bando.pk}}">
            <i class="pencil alternate icon"></i>
            Domanda non completa
        </div>
        {% endif %}

    {% elif not domanda_bando.bando.presentazione_domande_scaduta %}

        {% if domanda_bando.rettificabile %}
        <div class="ui right floated orange button lockbutton" id="but_rettifica_domanda_{{domanda_bando.pk}}">
            <i class="pencil alternate icon"></i>
            Riapri la domanda per una Rettifica
        </div>
        {% endif %}

    {% endif %}

</div>

gestione_peo/templates/commissione_dashboard_domanda_extended.html
{% extends 'commissione_dashboard_domanda.html' %}

{% load domande_peo_tags %}
{% load static %}

{% block js_head %}
<script type="text/javascript" src="{% static '/js/textarea-autosize_legacy.js' %}"></script>
{% endblock js_head %}

{% block extended_compressed_view %}
<a href="{% url 'gestione_peo:commissione_domanda_manage_extended' commissione_id=commissione.pk domanda_id=domanda_bando.pk %}">
    <button class="ui primary basic button">
        <i class="compress icon"></i>
        Visualizzazione compressa
    </button>
</a>
{% endblock %}

{% block elenco_moduli_domanda %}
{% for modulo_domanda_bando in domanda_bando.modulodomandabando_set.all %}
    <div class="ui raised {% if modulo_domanda_bando.disabilita %}red{% else %}blue{% endif %} segment" id="{{ modulo_domanda_bando.pk }}">
        {% if not modulo_domanda_bando.added_by_user %}
            <div class="ui warning message">
                  <i class="icon info circle"></i>
                  Inserito manualmente dai commissari
            </div>
        {% endif %}
        <h5>{{ modulo_domanda_bando.get_identificativo_veloce|upper }}</h3>
        <p style="color:#000">
            <i>
                {{ modulo_domanda_bando.descrizione_indicatore.indicatore_ponderato }}:
                ({{ modulo_domanda_bando.descrizione_indicatore.id_code }})
                {{ modulo_domanda_bando.descrizione_indicatore.nome }}
            </i>
        </p>
        <p style="color:#000">{{ modulo_domanda_bando.descrizione_indicatore.note_as_html|safe }}</p>
        <form class="ui form">
            {% domanda_bando_readonly modulo_domanda_bando as form %}

            {% for field in form %}
            <div class="field">
                {{ field.label_tag }}
                {{ field.errors }}
                {{ field }}
                {% if field.help_text %}
                <div class="ui help">
                    <p style="color: grey;">
                        <i>{{ field.help_text|safe }}</i>
                    </p>
                </div>
                {% endif %}
            </div>
            {% endfor %}
        </form>
        {% block allegati %}
            {% get_allegati_modulo modulo_domanda_bando as allegati_modulo %}
            {% if allegati_modulo %}
            <div class="ui section divider" ></div>
            <div>
                <label style="color:#000;">Allegati</label>
                {% for k,v in allegati_modulo %}
                    <div class="field" style="color:#000;">
                        <p style="margin-bottom: 3px; margin-top: 7px;">{{k}}</p>
                        <a style="color: #4183c4;"
                           href="{% url 'domande_peo:download_allegato' bando_id=bando.slug modulo_compilato_id=modulo_domanda_bando.pk allegato=k  %}">{{v}}</a>
                    </div>
                {% endfor %}
            </div>
            {% endif %}
        {% endblock allegati %}

        {% include 'commissione_disabilita_inserimento_form.html' with disable_input=modulo_domanda_bando.pk %}

        <div style="text-align:right">
            {% if not modulo_domanda_bando.added_by_user %}
            <button class="ui negative button" id="cancella_ind_{{ modulo_domanda_bando.pk }}">
                <i class="trash alternate icon"></i>
                Cancella
            </button>

            <a style="color: white;"
               href="{% url 'gestione_peo:commissione_modulo_domanda_modifica' commissione_id=commissione.pk domanda_id=domanda_bando.pk modulo_id=modulo_domanda_bando.pk %}">
                <div class="ui primary button">
                    <i class="edit icon"></i>
                    Modifica
                </div>
            </a>
            {% endif %}
            <a href="{% url 'gestione_peo:commissione_domanda_duplica_titolo' commissione_id=commissione.pk domanda_id=domanda_bando.pk modulo_id=modulo_domanda_bando.pk %}">
                <div class="ui primary button">
                    <i class="copy icon"></i>
                    Duplica inserimento
                </div>
            </a>
        </div>

    </div>
{% endfor %}
{% endblock elenco_moduli_domanda %}

gestione_peo/templates/commissione_modal_domanda.html
<!-- Disabilita domanda -->
<div class="ui basic modal" id="modal_disabilita_domanda">
    <div class="ui icon header">
        <i class="trash icon"></i>
        Disabilitazione domanda
        <h5>
            <b>{{ domanda_bando }}</b>
        </h5>
    </div>
    <div class="content">
        <p>Stai per disabilitare questa
            domanda, creata giorno {{ domanda_bando.created }},
            dal dipendente {{ domanda_bando.dipendente }}.
        </p>
        <h5>
            Sei veramente sicuro di questa scelta?
        </h5>
    </div>
    <div class="actions">
        <div class="ui white basic cancel inverted button">
            <i class="remove icon"></i>
            No
        </div>

        <a style="color: white;" href="{% url 'gestione_peo:commissione_disabilita_domanda' commissione_id=commissione.pk domanda_id=domanda_bando.pk %}">
            <div class="ui red ok inverted button">
                <i class="checkmark icon"></i>
                Si, sono sicuro: DISABILITA
            </div>
        </a>

    </div>
</div>
<!-- Abilita domanda -->
<div class="ui basic modal" id="modal_abilita_domanda">
    <div class="ui icon header">
        <i class="trash icon"></i>
        Abilitazione domanda
        <h5>
            <b>{{ domanda_bando }}</b>
        </h5>
    </div>
    <div class="content">
        <p>Stai per bilitare questa
            domanda, creata giorno {{ domanda_bando.created }},
            dal dipendente {{ domanda_bando.dipendente }}.
        </p>
        <h5>
            Sei veramente sicuro di questa scelta?
        </h5>
    </div>
    <div class="actions">
        <div class="ui white basic cancel inverted button">
            <i class="remove icon"></i>
            No
        </div>

        <a style="color: white;" href="{% url 'gestione_peo:commissione_abilita_domanda' commissione_id=commissione.pk domanda_id=domanda_bando.pk %}">
            <div class="ui green ok inverted button">
                <i class="checkmark icon"></i>
                Si, sono sicuro: ABILITA
            </div>
        </a>

    </div>
</div>

{% for ins in domanda_bando.modulodomandabando_set.all %}
<div class="ui basic modal" id="modal_ind_{{ ins.pk }}">
    <div class="ui icon header">
        <i class="trash alternate icon"></i>
        Cancellazione inserimento
        <h5>
            <b>{{ ins.get_identificativo_veloce }}</b>
            <br>
            {{ ins.descrizione_indicatore.nome }}
        </h5>
    </div>
    <div class="content">
        <p>Stai per cancellare definitamente questo
            inserimento, creato giorno {{ ins.created }},
            dalla domanda {{ ins.domanda_bando.bando }}.
        </p>
        <h5>
            Sei veramente sicuro di questa scelta?
        </h5>
    </div>
    <div class="actions">
        <div class="ui white basic cancel inverted button">
            <i class="remove icon"></i>
            No
        </div>

        <a style="color: white;" href="{% url 'gestione_peo:commissione_cancella_titolo' commissione_id=commissione.pk domanda_id=ins.domanda_bando.pk modulo_id=ins.pk  %}">
            <div class="ui red ok inverted button">
                <i class="checkmark icon"></i>
                Si, sono sicuro: CANCELLA
            </div>
        </a>

    </div>
</div>
{% endfor %}

gestione_peo/templates/commissione_modulo_form.html
{% extends 'modulo_form.html' %}

{% block page_sub_title %}
<h2 class="ui header">Integrazione domanda {{ domanda_bando }} </h2>
{% endblock page_sub_title %}

{% block formbuttons_back %}
    <a href="{% url 'gestione_peo:commissione_domanda_manage' commissione_id=commissione.pk domanda_id=domanda_bando.pk %}">
        <div class="ui button">
            <i class="fast backward icon"></i>
            Torna alla Domanda
        </div>
    </a>
    <a href="{% url 'gestione_peo:commissione_domanda_scegli_titolo' commissione_id=commissione.pk domanda_id=domanda_bando.pk %}">
        <div class="ui button">
            <i class="step backward icon"></i>
            Torna indietro
        </div>
    </a>
{% endblock formbuttons_back %}

{% block content_top %}
<div class="ui grid stackable grid">
    <div class="twelve wide column" id="sticky_reference_panel">
{% endblock content_top %}
{% block content_bottom %}
    </div>
    <div class="four wide column">
        {% include "right_main_menu.html" %}
    </div>
</div>
{% endblock content_bottom %}

gestione_peo/templates/commissione_modulo_form_modifica.html
{% extends 'modulo_form_modifica.html' %}

{% load django_form_builder_tags %}
{% load i18n %}

{% block page_sub_title %}
<h2 class="ui header">Domanda {{ domanda_bando }}</h2>
{% endblock page_sub_title %}

{% block top_buttons %}
    {% include 'commissione_disabilita_inserimento_form.html' with disable_input=1 %}
{% endblock top_buttons %}

{% block content_size %}
    <div class="ui section divider white"></div>
    <div class="ui grid stackable grid">
        <div class="twelve wide column" id="sticky_reference_panel">
{% endblock content_size %}

{% block close_content_size_right_menu %}
        </div>

        <div class="four wide column">
            {% include "right_main_menu.html" %}
        </div>
    </div>
{% endblock close_content_size_right_menu %}

{% block add_another %}{% endblock add_another %}

{% block allegati %}
    <!--
    Se ci sono allegati inseriti
    -->
    {% if allegati %}
        <h3>Allegati:</h3>
        <table class="ui compact striped table">
            <tbody>
                <tr>
                    <th>{% trans "Nome Allegato" %}</th>
                    <th>{% trans "Nome File" %}</th>
                    <th>{% trans "Altre info" %}</th>
                    <th></th>
                    {% if not modulo_domanda_bando.added_by_user %}
                        <th></th>
                    {% endif %}
                </tr>
                {% for k,v in allegati.items %}
                    <tr>
                        <td class="collapsing">
                            <b>{{k}}</b>
                        </td>
                        <td>{{v}}</td>
                        <td>
                        {% get_attachment_sign_details form_allegati path_allegati k v as sign_details %}
                        {% if sign_details %}
                            <ul>
                            {% for kk, vv in sign_details.items %}
                                <li>{{ kk }}: {{ vv }}</li>
                            {% endfor %}
                            </ul>
                        {% else %}
                        -
                        {% endif %}
                        </td>
                        <td class="right aligned collapsing">
                            <a download href="{% url 'gestione_peo:commissione_download_allegato' commissione_id=commissione.pk domanda_id=domanda_bando.pk modulo_id=modulo_domanda_bando.pk allegato=k  %}">
                                <div class="ui small button">
                                    <i class="icon download"></i>
                                    Vedi allegato
                                </div>
                            </a>
                        </td>
                        {% if not modulo_domanda_bando.added_by_user %}
                        <!--
                        Se la domanda è modificabile,
                        il pulsante Rimuovi allegato viene mostrato
                        -->
                            <td class="right aligned collapsing">
                                <a id="cancella_allegato_{{ k }}" href="#">
                                    <div class="ui negative small button">
                                        <i class="icon trash"></i>
                                        Rimuovi allegato
                                    </div>
                                </a>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <!--
        Modal delete (solo se la domanda è modificabile)
        -->
        {% if not modulo_domanda_bando.added_by_user %}
            {% for k,v in allegati.items %}
                <div class="ui basic modal" id="modal_allegato_{{ k }}">
                    <div class="ui icon header">
                        <i class="trash alternate icon"></i>
                        Cancellazione allegato
                        <h5>{{ k }}: {{ v }}</h5>
                    </div>
                    <div class="content">
                        <p>Stai per cancellare definitamente questo
                            allegato, creato giorno {{ modulo_domanda_bando.created }},
                            dalla domanda {{ modulo_domanda_bando.domanda_bando.bando }}.
                        </p>
                        <h5>
                            Sei veramente sicuro di questa scelta?
                        </h5>
                    </div>
                    <div class="actions">
                        <div class="ui white basic cancel inverted button">
                            <i class="remove icon"></i>
                            No
                        </div>

                        <a style="color: white;" href="{% url 'gestione_peo:commissione_elimina_allegato' allegato=k commissione_id=commissione.pk domanda_id=modulo_domanda_bando.domanda_bando.pk modulo_id=modulo_domanda_bando.pk  %}">
                            <div class="ui red ok inverted button">
                                <i class="checkmark icon"></i>
                                Si, sono sicuro: CANCELLA
                            </div>
                        </a>

                    </div>
                </div>
            {% endfor %}
        {% endif %}
    {% endif %}
{% endblock allegati %}

{% block formbuttons_back %}
    <a href="{% url 'gestione_peo:commissione_domanda_manage' commissione_id=commissione.pk domanda_id=domanda_bando.pk %}">
        <div class="ui button">
            <i class="step backward icon"></i>
            Torna alla Domanda
        </div>
    </a>
{% endblock formbuttons_back %}

{% block formbuttons_pdf %}
    <a href="{% url 'domande_peo:download_modulo_inserito_pdf' bando_id=bando.slug modulo_compilato_id=modulo_domanda_bando.pk %}">
        <div class="ui button">
            <i class="file pdf icon"></i>
            Scarica PDF
        </div>
    </a>

    <a href="{% url 'gestione_peo:commissione_domanda_duplica_titolo' commissione_id=commissione.pk domanda_id=domanda_bando.pk modulo_id=modulo_domanda_bando.pk %}">
        <div class="ui primary button">
            <i class="copy icon"></i>
            Duplica inserimento
        </div>
    </a>
{% endblock formbuttons_pdf %}

{% block submit_button %}
    {% if not modulo_domanda_bando.added_by_user %}
        <input class="ui button positive" type="submit" value="Salva" />
    {% endif %}
{% endblock submit_button %}

{% block bottom_scripts %}
    {{ block.super }}
    {% if allegati and not modulo_domanda_bando.added_by_user %}
        <script type="text/javascript">
            $(function () {
                {% for k,v in allegati.items %}
                $("#cancella_allegato_{{ k }}").click(function () {
                    $('#modal_allegato_{{ k }}')
                        .modal('show');
                });
                {% endfor %}
            });
        </script>
    {% endif %}
{% endblock %}